package com.customannotation.enums;

public enum ProblemTag {
    ARRAY, STRING, HASH_TABLE, DYNAMIC_PROGRAMMING, MATH, SORTING, GREEDY,
    DEPTH_FIRST_SEARCH, DATABASE, BINARY_SEARCH, MATRIX, TREE, BREADTH_FIRST_SEARCH,
    BIT_MANIPULATION, TWO_POINTERS, PREFIX_SUM, HEAP, BINARY_TREE, SIMULATION,
    STACK, GRAPH, COUNTING, SLIDING_WINDOW, DESIGN, BACKTRACKING, ENUMERATION,
    UNION_FIND, LINKED_LIST, ORDERED_SET, NUMBER_THEORY, MONOTONIC_STACK,
    SEGMENT_TREE, TRIE, COMBINATORICS, BITMASK, QUEUE, DIVIDE_AND_CONQUER, RECURSION,
    BINARY_INDEXED_TREE, GEOMETRY, MEMOIZATION, BINARY_SEARCH_TREE, HASH_FUNCTION,
    STRING_MATCHING, TOPOLOGICAL_SORT, SHORTEST_PATH, ROLLING_HASH, GAME_THEORY,
    INTERACTIVE, DATA_STREAM, MONOTONIC_QUEUE, BRAINTEASER, RANDOMIZED, MERGE_SORT,
    DOUBLY_LINKED_LIST, COUNTING_SORT, ITERATOR, CONCURRENCY, PROBABILITY_AND_STATISTICS,
    QUICKSELECT, SUFFIX_ARRAY, BUCKET_SORT, MINIMUM_SPANNING_TREE, LINE_SWEEP,
    SHELL, RESERVOIR_SAMPLING, STRONGLY_CONNECTED_COMPONENT, EULERIAN_CIRCUIT,
    RADIX_SORT, REJECTION_SAMPLING, BICONNECTED_COMPONENT
}
